### ISSUE TITLE
set permissions for authentication 

### ISSUE THREAD

**Issue by gabriel-vieira** [krachot/passport-deezer#1]
Hi,
Someone can tell me if this module handle the permissions for authentication ?

My URL must be like this : https://connect.deezer.com/oauth/auth.php?app_id=YOUR_APP_ID&redirect_uri=YOUR_REDIRECT_URI&perms=basic_access,email

**Comment by matthieubozec** [comment]
Hi Gabriel,

Deezer use "perms" parameter in order to handle permissions, unlike other strategies whose use "scope" parameter.
I just publish a new version 0.2.0, which handle permissions. 
See this commit https://github.com/krachot/passport-deezer/commit/8608a712d7f3b7e57b596f52281ff54e8732fe94

Cheers.
